// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default options for Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Google-specific options.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_q4wsItgw_VfymMlQrOEAIhkOYoMWp4',
    appId: '1:64681796501:android:bdef1650c55aa075b48c9c',
    messagingSenderId: '64681796501',
    projectId: 'giet-smart-8a818',
    storageBucket: 'giet-smart-8a818.firebasestorage.app',
  );

  /// Apple-specific options.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  /// Web-specific options.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW_q4wsItgw_VfymMlQrOEAIhkOYoMWp4',
    appId: '1:64681796501:web:f0151dc7a115d406b48c9c',
    messagingSenderId: '64681796501',
    projectId: 'giet-smart-8a818',
    authDomain: 'giet-smart-8a818.firebaseapp.com',
    storageBucket: 'giet-smart-8a818.firebasestorage.app',
  );
}
